# These are supported funding model platforms

# github: [FiniteLooper]
# patreon:
# open_collective:
# ko_fi:
# tidelift:
# community_bridge:
# liberapay:
# issuehunt:
# otechie:
# lfx_crowdfunding:
custom:
  - https://www.paypal.com/paypalme/chrisbarr
